window.PREGUNTAS = [
  { "pregunta": "¿Qué te gusta que la gente note de vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué cosa tuya te gustaría que se entienda más?", "categoria": "conocernos" },
  { "pregunta": "¿Qué es algo que antes te avergonzaba y ahora no?", "categoria": "conocernos" },
  { "pregunta": "¿Qué aprendiste sobre vos este último año?", "categoria": "conocernos" },
  { "pregunta": "¿Qué es algo que nadie sabe de vos pero te gustaría compartir?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu personalidad cambió más con el tiempo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué persona te influyó más en quién sos hoy?", "categoria": "conocernos" },
  { "pregunta": "¿Qué creés que la gente asume de vos y no es cierto?", "categoria": "conocernos" },
  { "pregunta": "¿Qué frase te representa hoy?", "categoria": "conocernos" },
  { "pregunta": "¿Qué es lo primero que notás en alguien?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te hace sentir cómodo en un grupo nuevo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te gustaría que la gente pregunte más?", "categoria": "conocernos" },
  { "pregunta": "¿Qué aprendiste a valorar recién de grande?", "categoria": "conocernos" },
  { "pregunta": "¿Qué no tolerás en otra persona?", "categoria": "conocernos" },
  { "pregunta": "¿Qué aprendiste de vos este mes?", "categoria": "conocernos" },
  { "pregunta": "¿En qué momentos sentís paz?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te cuesta pedir?", "categoria": "conocernos" },
  { "pregunta": "¿Qué emoción te cuesta mostrar?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu rutina es sagrada para vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué creés que la gente malinterpreta sobre vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te hace sentir realmente vivo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué actividad te cura el alma?", "categoria": "conocernos" },
  { "pregunta": "¿Qué ritual personal disfrutás?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu historia te gusta contar?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte del día te representa mejor?", "categoria": "conocernos" },
  { "pregunta": "¿Qué frase te gustaría tatuarte?", "categoria": "conocernos" },
  { "pregunta": "¿Qué cosa simple te hace inmensamente feliz?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu día disfrutás más sin darte cuenta?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te calma casi de inmediato?", "categoria": "conocernos" },
  { "pregunta": "¿Qué costumbre tuya dice mucho de vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te hace sentir en casa?", "categoria": "conocernos" },
  { "pregunta": "¿Qué cosa simple valorás mucho?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu personalidad sale con muy poca gente?", "categoria": "conocernos" },
  { "pregunta": "¿Qué objeto cotidiano llevás siempre encima y por qué dice tanto de vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué sonido del día a día te genera una calma instantánea?", "categoria": "conocernos" },
  { "pregunta": "¿Qué app o función del celular usás de forma obsesiva pero no admitís?", "categoria": "conocernos" },
  { "pregunta": "¿Qué ropa o prenda te hace sentir inmediatamente más vos mismo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué rutina matadora tenés que nadie imaginaría?", "categoria": "conocernos" },

  { "pregunta": "¿Cuál es una verdad difícil que tuviste que aceptar?", "categoria": "profundas" },
  { "pregunta": "¿Qué herida del pasado seguís trabajando?", "categoria": "profundas" },
  { "pregunta": "¿Qué conversación pendiente tenés con alguien?", "categoria": "profundas" },
  { "pregunta": "¿Qué te cuesta perdonarte?", "categoria": "profuntas" },
  { "pregunta": "¿Qué te da miedo del futuro?", "categoria": "profundas" },
  { "pregunta": "Si pudieras cambiar una sola decisión, ¿cuál sería?", "categoria": "profundas" },
  { "pregunta": "¿Qué te impide avanzar hoy?", "categoria": "profundas" },
  { "pregunta": "¿Qué te gustaría cambiar del mundo si pudieras?", "categoria": "profundas" },
  { "pregunta": "¿Qué pensamiento repetís demasiado seguido?", "categoria": "profundas" },
  { "pregunta": "Si pudieras borrar un mal recuerdo, ¿lo harías?", "categoria": "profundas" },
  { "pregunta": "¿Qué prejuicio te sorprende todavía tener?", "categoria": "profundas" },
  { "pregunta": "¿Qué cosa te gustaría soltar hoy mismo?", "categoria": "profundas" },
  { "pregunta": "¿Qué emoción preferís evitar?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de tu vida merece un reinicio?", "categoria": "profundas" },
  { "pregunta": "¿Qué situación te hizo valorar más lo que tenés?", "categoria": "profundas" },
  { "pregunta": "¿Qué mensaje te gustaría dejarle al mundo?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de tu vida sentís que todavía está en pausa?", "categoria": "profundas" },
  { "pregunta": "¿Qué miedo aprendiste a disimular bien?", "categoria": "profundas" },
  { "pregunta": "¿Qué verdad evitaste durante mucho tiempo?", "categoria": "profundas" },
  { "pregunta": "¿Qué te dolió más de lo que admitís?", "categoria": "profundas" },
  { "pregunta": "¿Qué conversación sabés que necesitás tener?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de vos necesitó más cuidado?", "categoria": "profundas" },
  { "pregunta": "¿Qué momento sentís que te definió?", "categoria": "profundas" },
  { "pregunta": "¿Qué promesa te hiciste alguna vez?", "categoria": "profundas" },
  { "pregunta": "¿Qué momento sentís que te transformó como persona?", "categoria": "profundas" },
  { "pregunta": "¿Qué pensamiento intrusivo aparece cuando estás solo en silencio?", "categoria": "profundas" },
  { "pregunta": "¿Qué éxito ajeno te genera una envidia sana que te motiva?", "categoria": "profundas" },
  { "pregunta": "¿Qué rol jugás en tu familia que te pesa más de lo que decís?", "categoria": "profundas" },
  { "pregunta": "¿Qué pregunta sobre tu vida evitás hacerte a vos mismo?", "categoria": "profundas" },
  { "pregunta": "¿Qué vacío sentís cuando todo está 'bien' en tu vida?", "categoria": "profundas" },

  { "pregunta": "¿Qué relación te sorprendió para bien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué amistad recuperaste o te gustaría recuperar?", "categoria": "relaciones" },
  { "pregunta": "¿Qué te enseñó tu última discusión?", "categoria": "relaciones" },
  { "pregunta": "¿Qué demostración de cariño te emociona más?", "categoria": "relaciones" },
  { "pregunta": "¿Qué agradecés de alguien cercano?", "categoria": "relaciones" },
  { "pregunta": "¿Qué conversación difícil tuviste y salió bien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué te hizo sentir acompañado últimamente?", "categoria": "relaciones" },
  { "pregunta": "¿Qué señal te muestra que una relación ya no te hace bien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué creés que das mucho en un vínculo?", "categoria": "relaciones" },
  { "pregunta": "¿Qué conversación te cambió un día difícil?", "categoria": "relaciones" },
  { "pregunta": "¿Qué cualidad valorás más en una amistad?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona fue tu refugio emocional?", "categoria": "relaciones" },
  { "pregunta": "¿Qué gesto tuyo muestra amor sin decirlo?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona te marcó con un gesto?", "categoria": "relaciones" },
  { "pregunta": "¿Qué vínculo te gustaría sanar?", "categoria": "relaciones" },
  { "pregunta": "¿Qué gesto te hace confiar en alguien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona te inspira y por qué?", "categoria": "relaciones" },
  { "pregunta": "¿Qué gesto te hace sentir realmente querido?", "categoria": "relaciones" },
  { "pregunta": "¿Qué vínculo te enseñó a decir que no?", "categoria": "relaciones" },
  { "pregunta": "¿Qué relación te cambió la forma de amar?", "categoria": "relaciones" },
  { "pregunta": "¿Qué aprendiste observando una pareja cercana?", "categoria": "relaciones" },
  { "pregunta": "¿Qué te cuesta pedir en una relación?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona te conoce mejor de lo que creés?", "categoria": "relaciones" },
  { "pregunta": "¿Qué silencio con alguien cercano te dice más que mil palabras?", "categoria": "relaciones" },
  { "pregunta": "¿Qué amigo te obliga a ser una mejor versión de vos sin decirlo?", "categoria": "relaciones" },
  { "pregunta": "¿Qué mensaje no enviado guardás en borradores hace meses?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona te genera una mezcla rara de admiración y distancia?", "categoria": "relaciones" },
  { "pregunta": "¿Qué detalle en alguien nuevo te hace pensar 'esta persona va a marcarme'?", "categoria": "relaciones" },

  { "pregunta": "¿Qué creencia tuviste que dejar atrás?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué decisión te cambió la vida?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué miedo superaste?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito dejaste atrás con orgullo?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué momento marcó un antes y un después?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué desafío estás enfrentando hoy?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué consejo no te sirvió nunca?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito te gustaría dejar pero no podés?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué aprendiste mirando a otras personas?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito te gustaría copiar de alguien?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué riesgo tomaste y valió la pena?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué aprendizaje te dio un fracaso?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué te enseñó un momento incómodo?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito nuevo querés incorporar pronto?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué desafío te gustaría superar pronto?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué aprendizaje repetiste varias veces hasta entenderlo?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué miedo venciste sin darte cuenta?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué error te enseñó más de lo que dolió?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito estás intentando cambiar ahora?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué aprendizaje te llegó tarde, pero llegó?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué parte de vos se volvió más fuerte?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué límite aprendiste a poner?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué versión tuya estás dejando atrás?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué habilidad aprendiste a los golpes y ahora usás todos los días?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué 'no' dijiste recientemente que te liberó más de lo esperado?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué libro o podcast te hizo cuestionar todo un fin de semana?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué pequeña disciplina incorporaste que cambió tu energía por completo?", "categoria": "crecimiento" },

  { "pregunta": "¿Qué sueño dejaste en pausa?", "categoria": "sueños" },
  { "pregunta": "¿Qué meta te asusta pero querés perseguir igual?", "categoria": "sueños" },
  { "pregunta": "¿Qué éxito no celebraste como deberías?", "categoria": "sueños" },
  { "pregunta": "Si todo saliera bien, ¿dónde te ves en 5 años?", "categoria": "sueños" },
  { "pregunta": "¿Qué proyecto te entusiasma hoy?", "categoria": "sueños" },
  { "pregunta": "¿Qué harías si no fallaras?", "categoria": "sueños" },
  { "pregunta": "¿Qué sueño no querés dejar morir?", "categoria": "sueños" },
  { "pregunta": "¿Qué proyecto te gustaría completar este año?", "categoria": "sueños" },
  { "pregunta": "¿Qué sueño infantil cumpliste de grande?", "categoria": "sueños" },
  { "pregunta": "¿Qué te gustaría aprender antes de morir?", "categoria": "sueños" },
  { "pregunta": "¿Qué decisión tomarías si no tuvieras miedo?", "categoria": "sueños" },
  { "pregunta": "¿Qué experiencia repetirías una y otra vez?", "categoria": "sueños" },
  { "pregunta": "¿Qué conversación te gustaría tener con tu yo del futuro?", "categoria": "sueños" },
  { "pregunta": "¿Qué sueño postergás por miedo y no por falta de ganas?", "categoria": "sueños" },
  { "pregunta": "¿Qué te gustaría intentar aunque salga mal?", "categoria": "sueños" },
  { "pregunta": "¿Qué vida alternativa imaginás a veces?", "categoria": "sueños" },
  { "pregunta": "¿Qué proyecto sentís más propio?", "categoria": "sueños" },
  { "pregunta": "¿Qué te gustaría animarte a decir que sí?", "categoria": "sueños" },
  { "pregunta": "¿Qué sueño te emociona solo pensarlo?", "categoria": "sueños" },
  { "pregunta": "¿Qué experiencia extrema te gustaría vivir aunque te dé vértigo solo imaginarla?", "categoria": "sueños" },
  { "pregunta": "¿Qué habilidad loca querés dominar solo por el placer de poder hacerlo?", "categoria": "sueños" },
  { "pregunta": "¿Qué ciudad o lugar te imaginás habitando temporalmente para reinventarte?", "categoria": "sueños" },
  { "pregunta": "¿Qué side project tenés en la cabeza que nadie sabe?", "categoria": "sueños" },

  { "pregunta": "¿Qué momento de tu infancia revivís con una sonrisa?", "categoria": "pasado" },
  { "pregunta": "¿Qué error del pasado te hizo evolucionar?", "categoria": "pasado" },
  { "pregunta": "¿Qué etapa de tu vida extrañás?", "categoria": "pasado" },
  { "pregunta": "¿Qué recuerdo atesorás?", "categoria": "pasado" },
  { "pregunta": "¿Qué persona te enseñó la mayor lección?", "categoria": "pasado" },
  { "pregunta": "¿Qué club o grupo marcó tu infancia?", "categoria": "pasado" },
  { "pregunta": "¿Qué olor te transporta a un recuerdo?", "categoria": "pasado" },
  { "pregunta": "¿Qué te hubiera gustado que te enseñen de chico?", "categoria": "pasado" },
  { "pregunta": "¿Qué lugar te marcó para siempre?", "categoria": "pasado" },
  { "pregunta": "¿Qué travesura recordás con nostalgia?", "categoria": "pasado" },
  { "pregunta": "¿Qué recuerdo te hace llorar sin querer?", "categoria": "pasado" },
  { "pregunta": "¿Qué error volverías a cometer?", "categoria": "pasado" },
  { "pregunta": "¿Qué momento te gustaría revivir solo una vez más?", "categoria": "pasado" },
  { "pregunta": "¿Qué error agradecés haber cometido?", "categoria": "pasado" },
  { "pregunta": "¿Qué recuerdo te formó sin que lo supieras?", "categoria": "pasado" },
  { "pregunta": "¿Qué parte de tu infancia te sigue acompañando?", "categoria": "pasado" },
  { "pregunta": "¿Qué persona del pasado entendés mejor hoy?", "categoria": "pasado" },
  { "pregunta": "¿Qué etapa cerraste recién con los años?", "categoria": "pasado" },
  { "pregunta": "¿Qué juguete o objeto de tu infancia buscarías hoy si pudieras?", "categoria": "pasado" },
  { "pregunta": "¿Qué profesor o adulto random te dijo algo que aún resuena?", "categoria": "pasado" },
  { "pregunta": "¿Qué verano o vacaciones de chico sentís que definió tu personalidad?", "categoria": "pasado" },

  { "pregunta": "¿Qué te hace sentir orgulloso de vos?", "categoria": "autoestima" },
  { "pregunta": "¿Qué parte de tu cuerpo aprendiste a querer?", "categoria": "autoestima" },
  { "pregunta": "¿Qué capacidad tuya subestimás?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cumplido te gusta recibir?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cosa hacés bien y pocos saben?", "categoria": "autoestima" },
  { "pregunta": "¿Qué momento reciente te llenó de energía?", "categoria": "autoestima" },
  { "pregunta": "¿Qué frase te repito siempre a vos mismo?", "categoria": "autoestima" },
  { "pregunta": "¿Qué es lo más auténtico de vos?", "categoria": "autoestima" },
  { "pregunta": "¿Qué logro tuyo subestimaste?", "categoria": "autoestima" },
  { "pregunta": "¿Qué rasgo tuyo no cambiarías nunca?", "categoria": "autoestima" },
  { "pregunta": "¿Qué logro personal te sorprende haber alcanzado?", "categoria": "autoestima" },
  { "pregunta": "¿Qué parte tuya defendés hoy sin culpa?", "categoria": "autoestima" },
  { "pregunta": "¿Qué logro tuyo no fue casualidad?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cualidad tuya te sostiene en días difíciles?", "categoria": "autoestima" },
  { "pregunta": "¿Qué versión tuya te gusta más?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cosa aprendiste a respetar de vos?", "categoria": "autoestima" },
  { "pregunta": "¿Qué fuerza descubriste en vos?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cumplido rechazaste internamente pero en el fondo sabés que es cierto?", "categoria": "autoestima" },
  { "pregunta": "¿Qué crisis manejaste tan bien que ni vos lo creés al recordarlo?", "categoria": "autoestima" },

  { "pregunta": "¿Qué mentira te creyeron durante años?", "categoria": "picantes" },
  { "pregunta": "¿Qué excusa usás demasiado?", "categoria": "picantes" },
  { "pregunta": "¿Qué error seguirías cometiendo?", "categoria": "picantes" },
  { "pregunta": "¿Qué parte de vos te cuesta mostrar?", "categoria": "picantes" },
  { "pregunta": "¿En qué situación perdés el control?", "categoria": "picantes" },
  { "pregunta": "¿Qué verdad ocultás por comodidad?", "categoria": "picantes" },
  { "pregunta": "¿Qué parte tuya evitás mostrar?", "categoria": "picantes" },
  { "pregunta": "¿Qué excusa te repetís demasiado?", "categoria": "picantes" },
  { "pregunta": "¿Qué límite rompiste alguna vez?", "categoria": "picantes" },
  { "pregunta": "¿Qué deseo te cuesta admitir?", "categoria": "picantes" },

  { "pregunta": "Si fueras un personaje de película, ¿cuál serías?", "categoria": "divertidas" },
  { "pregunta": "¿Qué talento inútil tenés?", "categoria": "divertidas" },
  { "pregunta": "¿Qué comida odiabas de chico y hoy te encanta?", "categoria": "divertidas" },
  { "pregunta": "¿Qué situación vergonzosa ahora te da risa?", "categoria": "divertidas" },
  { "pregunta": "Si tu vida fuera una serie, ¿cómo se llamaría?", "categoria": "divertidas" },
  { "pregunta": "¿Qué es lo más loco que hiciste sin pensar?", "categoria": "divertidas" },
  { "pregunta": "¿Qué miedo irracional tenés?", "categoria": "divertidas" },
  { "pregunta": "¿Qué lugar del mundo querés visitar sí o sí?", "categoria": "divertidas" },
  { "pregunta": "¿Qué cosa ridícula te da felicidad?", "categoria": "divertidas" },
  { "pregunta": "¿Qué manía tuya es inexplicable?", "categoria": "divertidas" },
  { "pregunta": "¿Qué harías si nadie te juzgara por un día?", "categoria": "divertidas" },
  { "pregunta": "¿Qué talento inútil te salva del aburrimiento?", "categoria": "divertidas" },
  { "pregunta": "¿Qué costumbre rara tenés?", "categoria": "divertidas" },
  { "pregunta": "¿Qué teoría conspirativa medio en broma defendés cuando estás aburrido?", "categoria": "divertidas" },
  { "pregunta": "¿Qué trend de redes hiciste en secreto y nunca contarías?", "categoria": "divertidas" },

  { "pregunta": "Decí algo lindo del jugador a tu derecha.", "categoria": "retos" },
  { "pregunta": "Contá una mini anécdota de tu infancia.", "categoria": "retos" },
  { "pregunta": "Mostrá una foto que te represente.", "categoria": "retos" },
  { "pregunta": "Decí una frase que te marcó.", "categoria": "retos" },
  { "pregunta": "Dale un consejo sincero a alguien de la mesa.", "categoria": "retos" },
  { "pregunta": "Decí una virtud de cada persona en la mesa.", "categoria": "retos" },
  { "pregunta": "Contá algo bueno que te haya pasado hoy.", "categoria": "retos" },
  { "pregunta": "Mandá un mensaje lindo a alguien.", "categoria": "retos" },
  { "pregunta": "Aplaudí a alguien por algo que hizo bien.", "categoria": "retos" },

  { "pregunta": "¿Qué fue lo mejor que te pasó esta semana?", "categoria": "niños" },
  { "pregunta": "¿Qué superpoder te gustaría tener?", "categoria": "niños" },
  { "pregunta": "¿Qué te pone triste?", "categoria": "niños" },
  { "pregunta": "¿Qué persona te hace sentir seguro?", "categoria": "niños" },
  { "pregunta": "¿Qué cosa aprendiste hoy?", "categoria": "niños" },
  { "pregunta": "¿Qué te hace reír mucho?", "categoria": "niños" },
  { "pregunta": "¿Qué te gusta hacer cuando estás aburrido?", "categoria": "niños" },
  { "pregunta": "¿Qué te da miedo por la noche?", "categoria": "niños" },
  { "pregunta": "¿Qué cosa aprendiste jugando?", "categoria": "niños" },
    { "pregunta": "¿Qué aroma cotidiano te pone de buen humor sin falla?", "categoria": "conocernos" },
  { "pregunta": "¿Qué canción random del pasado te hace cantar a gritos cuando estás solo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué notificación del celular te genera ansiedad instantánea?", "categoria": "conocernos" },
  { "pregunta": "¿Qué bebida o comida asociás con 'premio personal' después de un día duro?", "categoria": "conocernos" },
  { "pregunta": "¿Qué gesto involuntario hacés cuando estás concentrado?", "categoria": "conocernos" },

  { "pregunta": "¿Qué oportunidad perdida seguís revisando en tu cabeza de noche?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de tu éxito actual te hace sentir un poco impostor?", "categoria": "profundas" },
  { "pregunta": "¿Qué relación familiar complicada aceptaste que no va a cambiar?", "categoria": "profundas" },
  { "pregunta": "¿Qué deseo egoísta tenés que no contás ni a tus más cercanos?", "categoria": "profundas" },
  { "pregunta": "¿Qué miedo disfrazás de 'practicidad' para no enfrentar?", "categoria": "profundas" },

  { "pregunta": "¿Qué persona te hace hablar más de lo normal sin darte cuenta?", "categoria": "relaciones" },
  { "pregunta": "¿Qué amigo del pasado eliminaste en silencio y por qué?", "categoria": "relaciones" },
  { "pregunta": "¿Qué cumplido de alguien cercano te dolió porque tenía razón?", "categoria": "relaciones" },
  { "pregunta": "¿Qué dinámica repetís en tus vínculos sin querer?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona te hace sentir 'visto' con solo una mirada?", "categoria": "relaciones" },

  { "pregunta": "¿Qué app o herramienta digital cambió cómo organizás tu vida?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué 'sí' forzado te abrió puertas inesperadas?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué frase de un desconocido en internet te pegó fuerte?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué rutina mínima de 5 minutos te salva los días caóticos?", "categoria": "crecimiento" },

  { "pregunta": "¿Qué curso o taller random te gustaría tomar solo por curiosidad?", "categoria": "sueños" },
  { "pregunta": "¿Qué aventura de un día perfecto armarías si tuvieras plata ilimitada?", "categoria": "sueños" },
  { "pregunta": "¿Qué idioma querés aprender solo para consumir contenido original?", "categoria": "sueños" },
  { "pregunta": "¿Qué hobby abandonado te pica retomar en secreto?", "categoria": "sueños" },

  { "pregunta": "¿Qué libro o película de chico te hizo ver el mundo distinto?", "categoria": "pasado" },
  { "pregunta": "¿Qué frase de un familiar mayor repetís sin darte cuenta?", "categoria": "pasado" },
  { "pregunta": "¿Qué fracaso escolar o deportivo te marcó para bien al final?", "categoria": "pasado" },

  { "pregunta": "¿Qué habilidad social tuya rescatás en situaciones tensas?", "categoria": "autoestima" },
  { "pregunta": "¿Qué defecto tuyo terminaste convirtiendo en ventaja?", "categoria": "autoestima" },

  { "pregunta": "¿Qué comida combinás de forma rara que defenderías a muerte?", "categoria": "divertidas" },
  { "pregunta": "¿Qué video o meme viejo mirás en loop cuando estás bajón?", "categoria": "divertidas" },
    { "pregunta": "¿Qué foto vieja en tu celular mirás cuando estás melancólico?", "categoria": "pasado" },
  { "pregunta": "¿Qué canción te hace cerrar los ojos y viajar a otro momento de tu vida?", "categoria": "pasado" },
  { "pregunta": "¿Qué objeto guardás aunque ya no sirva para nada, solo porque te trae recuerdos?", "categoria": "pasado" },
  { "pregunta": "¿Qué versión tuya de hace unos años extrañás un poquito?", "categoria": "pasado" },
  { "pregunta": "¿Qué tarde de lluvia perfecta recordás con todo detalle?", "categoria": "pasado" },

  { "pregunta": "¿Qué pequeño lujo te das cuando nadie te ve?", "categoria": "conocernos" },
  { "pregunta": "¿Qué serie o película reves una y otra vez solo para sentirte acompañado?", "categoria": "conocernos" },
  { "pregunta": "¿Qué ruido blanco te ayuda a dormir o a concentrarte?", "categoria": "conocernos" },
  { "pregunta": "¿Qué mensaje viejo de alguien guardás y releés de vez en cuando?", "categoria": "conocernos" },
  { "pregunta": "¿Qué estación del año te representa emocionalmente?", "categoria": "conocernos" },

  { "pregunta": "¿Qué miedo de chico seguís teniendo un poco, aunque sea ridículo?", "categoria": "divertidas" },
  { "pregunta": "¿Qué personaje de dibujitos serías si tuvieras que elegir uno para toda la vida?", "categoria": "divertidas" },
  { "pregunta": "¿Qué comida te transporta directo a la casa de tu abuela o alguien querido?", "categoria": "divertidas" },
  { "pregunta": "¿Qué baile vergonzoso hacés cuando estás solo y suena TU canción?", "categoria": "divertidas" },
  { "pregunta": "¿Qué apodo viejo te saca una sonrisa aunque te dé vergüenza?", "categoria": "divertidas" },

  { "pregunta": "¿Qué abrazo recordás como si hubiera sido ayer?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona ya no está pero sentís que igual te acompaña?", "categoria": "relaciones" },
  { "pregunta": "¿Qué 'te quiero' no dicho pesó más que los que sí dijiste?", "categoria": "relaciones" },
  { "pregunta": "¿Qué risa compartida con alguien es de tus sonidos favoritos del mundo?", "categoria": "relaciones" },
  { "pregunta": "¿Qué amigo te conoce desde antes de que supieras quién eras?", "categoria": "relaciones" },

  { "pregunta": "¿Qué sueño recurrente tenés desde chico?", "categoria": "sueños" },
  { "pregunta": "¿Qué versión futura tuya te ilusiona aunque parezca lejana?", "categoria": "sueños" },
  { "pregunta": "¿Qué carta te gustaría escribirle a tu yo de dentro de 10 años?", "categoria": "sueños" },
  { "pregunta": "¿Qué lugar imaginario te inventaste de chico y todavía visitás mentalmente?", "categoria": "sueños" },

  { "pregunta": "¿Qué silencio compartido con alguien fue perfecto?", "categoria": "profundas" },
  { "pregunta": "¿Qué 'gracias' pendiente llevás cargando hace tiempo?", "categoria": "profundas" },
  { "pregunta": "¿Qué cicatriz (física o emocional) contás con orgullo ahora?", "categoria": "profundas" },
  { "pregunta": "¿Qué momento sentiste que el tiempo se detuvo un segundo?", "categoria": "profundas" },
  { "pregunta": "¿Qué despedida te dolió más de lo que mostraste?", "categoria": "profundas" },
  { "pregunta": "¿Qué pequeño acto de bondad ajena te salvó un día sin que lo supiera?", "categoria": "profundas" },

  { "pregunta": "¿Qué talento oculto tenés que solo sale con confianza o alcohol?", "categoria": "autoestima" },
  { "pregunta": "¿Qué día común sentiste que estabas exactamente donde tenías que estar?", "categoria": "autoestima" },
  { "pregunta": "¿Qué halago inesperado te dio alas por semanas?", "categoria": "autoestima" },

  { "pregunta": "¿Qué juego de la infancia jugarías mañana mismo si alguien te invita?", "categoria": "niños" },
  { "pregunta": "¿Qué invento loco harías si fueras científico por un día?", "categoria": "niños" },
  { "pregunta": "¿Qué animal serías por una semana y por qué?", "categoria": "niños" },

  { "pregunta": "¿Qué tradición inventada te gustaría empezar con tus seres queridos?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué libro te gustaría que lean todas las personas que querés?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué carta le escribirías a tu yo adolescente hoy?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué olor te hace sentir 'en casa' aunque no sea tu casa?", "categoria": "conocernos" },
    { "pregunta": "¿Qué ausencia sentís más fuerte en los días tranquilos?", "categoria": "profundas" },
  { "pregunta": "¿Qué versión de vos se quedó en una ciudad que ya no visitás?", "categoria": "profundas" },
  { "pregunta": "¿Qué palabra te hubiera gustado escuchar en un momento clave y nunca llegó?", "categoria": "profundas" },
  { "pregunta": "¿Qué paisaje miraste alguna vez sabiendo que algo terminaba?", "categoria": "profundas" },
  { "pregunta": "¿Qué foto no sacaste pero todavía ves perfectamente en tu cabeza?", "categoria": "profundas" },
  { "pregunta": "¿Qué aroma perdido te gustaría volver a oler una sola vez más?", "categoria": "profundas" },
  { "pregunta": "¿Qué carta nunca enviaste y todavía guardás en borrador mental?", "categoria": "profundas" },
  { "pregunta": "¿Qué voz ya no escuchás pero seguís reproduciendo en tu memoria?", "categoria": "profundas" },
  { "pregunta": "¿Qué tarde sola sentiste que el tiempo pasaba más lento que nunca?", "categoria": "profundas" },
  { "pregunta": "¿Qué abrazo breve duró más en tu cuerpo que en la realidad?", "categoria": "profundas" },
  { "pregunta": "¿Qué canción te duele escuchar pero igual la buscás de vez en cuando?", "categoria": "profundas" },
  { "pregunta": "¿Qué lugar vacío visitaste solo para sentir lo que ya no está?", "categoria": "profundas" },
  { "pregunta": "¿Qué sueño despierto tenías de chico que se fue apagando sin darte cuenta?", "categoria": "profundas" },
  { "pregunta": "¿Qué 'y si...' te visita más seguido en las noches silenciosas?", "categoria": "profundas" },
  { "pregunta": "¿Qué objeto de alguien querido guardás aunque duela mirarlo?", "categoria": "profundas" },
  { "pregunta": "¿Qué estación del año te pone más melancólico y por qué?", "categoria": "profundas" },
  { "pregunta": "¿Qué mirada de despedida todavía sentís clavada en algún lado?", "categoria": "profundas" },
  { "pregunta": "¿Qué risa ajena extrañás hasta que te aprieta el pecho?", "categoria": "profundas" },
  { "pregunta": "¿Qué camino caminaste sabiendo que no ibas a volver a hacerlo igual?", "categoria": "profundas" },
  { "pregunta": "¿Qué silencio después de una conversación te pesó más que las palabras?", "categoria": "profundas" },
  { "pregunta": "¿Qué luz de atardecer te hizo sentir que algo hermoso se iba para siempre?", "categoria": "profundas" },
  { "pregunta": "¿Qué nombre pronunciás en voz baja cuando nadie te escucha?", "categoria": "profundas" },
  { "pregunta": "¿Qué recuerdo feliz te entristece porque ya no puede repetirse?", "categoria": "profundas" },
  { "pregunta": "¿Qué tren, avión o colectivo dejaste pasar que todavía imaginás subiéndote?", "categoria": "profundas" },
  { "pregunta": "¿Qué versión de una persona querida se quedó congelada en tu memoria?", "categoria": "profundas" },
  { "pregunta": "¿Qué lluvia escuchaste desde adentro que te hizo sentir solo de la mejor manera?", "categoria": "profundas" },
  { "pregunta": "¿Qué 'te extraño' nunca dijiste en voz alta pero sentiste con todo el cuerpo?", "categoria": "profundas" },
  { "pregunta": "¿Qué cielo miraste alguna vez deseando que el tiempo se detuviera ahí?", "categoria": "profundas" },
  { "pregunta": "¿Qué puerta cerraste sabiendo que del otro lado quedaba una parte de vos?", "categoria": "profundas" },
  { "pregunta": "¿Qué melancolía bonita llevás siempre encima como un abrigo invisible?", "categoria": "profundas" }
]
