window.PREGUNTAS = [
  { "pregunta": "¿Qué te gusta que la gente note de vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué cosa tuya te gustaría que se entienda más?", "categoria": "conocernos" },
  { "pregunta": "¿Qué es algo que antes te avergonzaba y ahora no?", "categoria": "conocernos" },
  { "pregunta": "¿Qué aprendiste sobre vos este último año?", "categoria": "conocernos" },
  { "pregunta": "¿Qué es algo que nadie sabe de vos pero te gustaría compartir?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu personalidad cambió más con el tiempo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué persona te influyó más en quién sos hoy?", "categoria": "conocernos" },
  { "pregunta": "¿Qué creés que la gente asume de vos y no es cierto?", "categoria": "conocernos" },
  { "pregunta": "¿Qué frase te representa hoy?", "categoria": "conocernos" },
  { "pregunta": "¿Qué es lo primero que notás en alguien?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te hace sentir cómodo en un grupo nuevo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te gustaría que la gente pregunte más?", "categoria": "conocernos" },
  { "pregunta": "¿Qué aprendiste a valorar recién de grande?", "categoria": "conocernos" },
  { "pregunta": "¿Qué no tolerás en otra persona?", "categoria": "conocernos" },
  { "pregunta": "¿Qué aprendiste de vos este mes?", "categoria": "conocernos" },
  { "pregunta": "¿En qué momentos sentís paz?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te cuesta pedir?", "categoria": "conocernos" },

  { "pregunta": "¿Cuál es una verdad difícil que tuviste que aceptar?", "categoria": "profundas" },
  { "pregunta": "¿Qué herida del pasado seguís trabajando?", "categoria": "profundas" },
  { "pregunta": "¿Qué conversación pendiente tenés con alguien?", "categoria": "profundas" },
  { "pregunta": "¿Qué te cuesta perdonarte?", "categoria": "profundas" },
  { "pregunta": "¿Qué te da miedo del futuro?", "categoria": "profundas" },
  { "pregunta": "Si pudieras cambiar una sola decisión, ¿cuál sería?", "categoria": "profundas" },
  { "pregunta": "¿Qué te impide avanzar hoy?", "categoria": "profundas" },
  
  { "pregunta": "¿Qué relación te sorprendió para bien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué amistad recuperaste o te gustaría recuperar?", "categoria": "relaciones" },
  { "pregunta": "¿Qué te enseñó tu última discusión?", "categoria": "relaciones" },
  { "pregunta": "¿Qué demostración de cariño te emociona más?", "categoria": "relaciones" },
  { "pregunta": "¿Qué agradecés de alguien cercano?", "categoria": "relaciones" },
  { "pregunta": "¿Qué conversación difícil tuviste y salió bien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué te hizo sentir acompañado últimamente?", "categoria": "relaciones" },
  { "pregunta": "¿Qué señal te muestra que una relación ya no te hace bien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué creés que das mucho en un vínculo?", "categoria": "relaciones" },

  { "pregunta": "¿Qué creencia tuviste que dejar atrás?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué decisión te cambió la vida?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué miedo superaste?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito dejaste atrás con orgullo?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué momento marcó un antes y un después?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué desafío estás enfrentando hoy?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué consejo no te sirvió nunca?", "categoria": "crecimiento" },

  { "pregunta": "¿Qué sueño dejaste en pausa?", "categoria": "sueños" },
  { "pregunta": "¿Qué meta te asusta pero querés perseguir igual?", "categoria": "sueños" },
  { "pregunta": "¿Qué éxito no celebraste como deberías?", "categoria": "sueños" },
  { "pregunta": "Si todo saliera bien, ¿dónde te ves en 5 años?", "categoria": "sueños" },
  { "pregunta": "¿Qué proyecto te entusiasma hoy?", "categoria": "sueños" },

  { "pregunta": "¿Qué momento de tu infancia revivís con una sonrisa?", "categoria": "pasado" },
  { "pregunta": "¿Qué error del pasado te hizo evolucionar?", "categoria": "pasado" },
  { "pregunta": "¿Qué etapa de tu vida extrañás?", "categoria": "pasado" },
  { "pregunta": "¿Qué recuerdo atesorás?", "categoria": "pasado" },
  { "pregunta": "¿Qué persona te enseñó la mayor lección?", "categoria": "pasado" },

  { "pregunta": "¿Qué te hace sentir orgulloso de vos?", "categoria": "autoestima" },
  { "pregunta": "¿Qué parte de tu cuerpo aprendiste a querer?", "categoria": "autoestima" },
  { "pregunta": "¿Qué capacidad tuya subestimás?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cumplido te gusta recibir?", "categoria": "autoestima" },
  { "pregunta": "¿Qué cosa hacés bien y pocos saben?", "categoria": "autoestima" },

  { "pregunta": "¿Qué mentira te creyeron durante años?", "categoria": "picantes" },
  { "pregunta": "¿Qué excusa usás demasiado?", "categoria": "picantes" },
  { "pregunta": "¿Qué error seguirías cometiendo?", "categoria": "picantes" },
  { "pregunta": "¿Qué parte de vos te cuesta mostrar?", "categoria": "picantes" },
  { "pregunta": "¿En qué situación perdés el control?", "categoria": "picantes" },

  { "pregunta": "Si fueras un personaje de película, ¿cuál serías?", "categoria": "divertidas" },
  { "pregunta": "¿Qué talento inútil tenés?", "categoria": "divertidas" },
  { "pregunta": "¿Qué comida odiabas de chico y hoy te encanta?", "categoria": "divertidas" },
  { "pregunta": "¿Qué situación vergonzosa ahora te da risa?", "categoria": "divertidas" },
  { "pregunta": "Si tu vida fuera una serie, ¿cómo se llamaría?", "categoria": "divertidas" },

  { "pregunta": "Decí algo lindo del jugador a tu derecha.", "categoria": "retos" },
  { "pregunta": "Contá una mini anécdota de tu infancia.", "categoria": "retos" },
  { "pregunta": "Mostrá una foto que te represente.", "categoria": "retos" },
  { "pregunta": "Decí una frase que te marcó.", "categoria": "retos" },
  { "pregunta": "Dale un consejo sincero a alguien de la mesa.", "categoria": "retos" },
  { "pregunta": "¿Qué fue lo mejor que te pasó esta semana?", "categoria": "niños" },
  { "pregunta": "¿Qué superpoder te gustaría tener?", "categoria": "niños" },
  { "pregunta": "¿Qué te pone triste?", "categoria": "niños" },
  { "pregunta": "¿Qué persona te hace sentir seguro?", "categoria": "niños" },
  { "pregunta": "¿Qué cosa aprendiste hoy?", "categoria": "niños" },
  { "pregunta": "¿Qué te gustaría cambiar del mundo si pudieras?", "categoria": "profundas" },
  { "pregunta": "¿Qué emoción te cuesta mostrar?", "categoria": "conocernos" },
  { "pregunta": "¿Qué hábito te gustaría dejar pero no podés?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué harías si no fallaras?", "categoria": "sueños" },
  { "pregunta": "¿Qué momento reciente te llenó de energía?", "categoria": "autoestima" },
  { "pregunta": "¿Qué aprendiste mirando a otras personas?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué conversación te cambió un día difícil?", "categoria": "relaciones" },
  { "pregunta": "¿Qué es lo más loco que hiciste sin pensar?", "categoria": "divertidas" },
  { "pregunta": "¿Qué pensamiento repetís demasiado seguido?", "categoria": "profundas" },
  { "pregunta": "Si pudieras borrar un mal recuerdo, ¿lo harías?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de tu rutina es sagrada para vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué club o grupo marcó tu infancia?", "categoria": "pasado" },
  { "pregunta": "¿Qué olor te transporta a un recuerdo?", "categoria": "pasado" },
  { "pregunta": "¿Qué creés que la gente malinterpreta sobre vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué hábito te gustaría copiar de alguien?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué cualidad valorás más en una amistad?", "categoria": "relaciones" },
  { "pregunta": "¿Qué sueño no querés dejar morir?", "categoria": "sueños" },
  { "pregunta": "¿Qué miedo irracional tenés?", "categoria": "divertidas" },
  { "pregunta": "¿Qué momento sentís que te definió?", "categoria": "profundas" },
  { "pregunta": "¿Qué te hubiera gustado que te enseñen de chico?", "categoria": "pasado" },
  { "pregunta": "¿Qué promesa te hiciste alguna vez?", "categoria": "profundas" },
  { "pregunta": "¿Qué te hace sentir realmente vivo?", "categoria": "conocernos" },
  { "pregunta": "¿Qué persona fue tu refugio emocional?", "categoria": "relaciones" },
  { "pregunta": "¿Qué frase te repito siempre a vos mismo?", "categoria": "autoestima" },
  { "pregunta": "¿Qué riesgo tomaste y valió la pena?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué proyecto te gustaría completar este año?", "categoria": "sueños" },
  { "pregunta": "¿Qué lugar te marcó para siempre?", "categoria": "pasado" },
  { "pregunta": "¿Qué actividad te cura el alma?", "categoria": "conocernos" },
  { "pregunta": "¿Qué prejuicio te sorprende todavía tener?", "categoria": "profundas" },
  { "pregunta": "¿Qué es lo más auténtico de vos?", "categoria": "autoestima" },
  { "pregunta": "¿Qué ritual personal disfrutás?", "categoria": "conocernos" },
  { "pregunta": "¿Qué gesto tuyo muestra amor sin decirlo?", "categoria": "relaciones" },
  { "pregunta": "¿Qué aprendizaje te dio un fracaso?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué sueño infantil cumpliste de grande?", "categoria": "sueños" },
  { "pregunta": "¿Qué travesura recordás con nostalgia?", "categoria": "pasado" },
  { "pregunta": "¿Qué parte de tu historia te gusta contar?", "categoria": "conocernos" },
  { "pregunta": "¿Qué persona te marcó con un gesto?", "categoria": "relaciones" },
  { "pregunta": "¿Qué cosa te gustaría soltar hoy mismo?", "categoria": "profundas" },
  { "pregunta": "¿Qué logro tuyo subestimaste?", "categoria": "autoestima" },
  { "pregunta": "¿Qué te gustaría aprender antes de morir?", "categoria": "sueños" },
  { "pregunta": "¿Qué emoción preferís evitar?", "categoria": "profundas" },
  { "pregunta": "¿Qué te enseñó un momento incómodo?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito nuevo querés incorporar pronto?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué persona te inspira y por qué?", "categoria": "relaciones" },
  { "pregunta": "¿Qué parte de tu vida merece un reinicio?", "categoria": "profundas" },
  { "pregunta": "¿Qué decisión tomarías si no tuvieras miedo?", "categoria": "sueños" },
  { "pregunta": "¿Qué recuerdo te hace llorar sin querer?", "categoria": "pasado" },
  { "pregunta": "¿Qué rasgo tuyo no cambiarías nunca?", "categoria": "autoestima" },
  { "pregunta": "¿Qué aprendizaje repetiste varias veces hasta entenderlo?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué parte del día te representa mejor?", "categoria": "conocernos" },
  { "pregunta": "¿Qué frase te gustaría tatuarte?", "categoria": "conocernos" },
  { "pregunta": "¿Qué momento sentís que te transformó como persona?", "categoria": "profundas" },
  { "pregunta": "¿Qué vínculo te gustaría sanar?", "categoria": "relaciones" },
  { "pregunta": "¿Qué experiencia repetirte una y otra vez?", "categoria": "sueños" },
  { "pregunta": "¿Qué cosa simple te hace inmensamente feliz?", "categoria": "conocernos" },
  { "pregunta": "¿Qué desafío te gustaría superar pronto?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué error volverías a cometer?", "categoria": "pasado" },
  { "pregunta": "¿Qué situación te hizo valorar más lo que tenés?", "categoria": "profundas" },
  { "pregunta": "¿Qué gesto te hace confiar en alguien?", "categoria": "relaciones" },
  { "pregunta": "¿Qué logro personal te sorprende haber alcanzado?", "categoria": "autoestima" },
  { "pregunta": "¿Qué conversación te gustaría tener con tu yo del futuro?", "categoria": "sueños" },
  { "pregunta": "¿Qué lugar del mundo querés visitar sí o sí?", "categoria": "divertidas" },
  { "pregunta": "¿Qué miedo venciste sin darte cuenta?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué mensaje te gustaría dejarle al mundo?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de tu día disfrutás más sin darte cuenta?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te calma casi de inmediato?", "categoria": "conocernos" },
  { "pregunta": "¿Qué costumbre tuya dice mucho de vos?", "categoria": "conocernos" },
  { "pregunta": "¿Qué te hace sentir en casa?", "categoria": "conocernos" },
  { "pregunta": "¿Qué cosa simple valorás mucho?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu personalidad sale con muy poca gente?", "categoria": "conocernos" },
  { "pregunta": "¿Qué parte de tu vida sentís que todavía está en pausa?", "categoria": "profundas" },
  { "pregunta": "¿Qué miedo aprendiste a disimular bien?", "categoria": "profundas" },
  { "pregunta": "¿Qué verdad evitaste durante mucho tiempo?", "categoria": "profundas" },
  { "pregunta": "¿Qué te dolió más de lo que admitís?", "categoria": "profundas" },
  { "pregunta": "¿Qué conversación sabés que necesitás tener?", "categoria": "profundas" },
  { "pregunta": "¿Qué parte de vos necesitó más cuidado?", "categoria": "profundas" },
  { "pregunta": "¿Qué gesto te hace sentir realmente querido?", "categoria": "relaciones" },
  { "pregunta": "¿Qué vínculo te enseñó a decir que no?", "categoria": "relaciones" },
  { "pregunta": "¿Qué relación te cambió la forma de amar?", "categoria": "relaciones" },
  { "pregunta": "¿Qué aprendiste observando una pareja cercana?", "categoria": "relaciones" },
  { "pregunta": "¿Qué te cuesta pedir en una relación?", "categoria": "relaciones" },
  { "pregunta": "¿Qué persona te conoce mejor de lo que creés?", "categoria": "relaciones" },
  { "pregunta": "¿Qué error te enseñó más de lo que dolió?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué hábito estás intentando cambiar ahora?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué aprendizaje te llegó tarde, pero llegó?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué parte de vos se volvió más fuerte?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué límite aprendiste a poner?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué versión tuya estás dejando atrás?", "categoria": "crecimiento" },
  { "pregunta": "¿Qué sueño postergás por miedo y no por falta de ganas?", "categoria": "sueños" },
  { "pregunta": "¿Qué te gustaría intentar aunque salga mal?", "categoria": "sueños" },
  { "pregunta": "¿Qué vida alternativa imaginás a veces?", "categoria": "sueños" },
  { "pregunta": "¿Qué proyecto sentís más propio?", "categoria": "sueños" },
  { "pregunta": "¿Qué te gustaría animarte a decir que sí?", "categoria": "sueños" },
  { "pregunta": "¿Qué sueño te emociona solo pensarlo?", "categoria": "sueños" },
  { "pregunta": "¿Qué momento te gustaría revivir solo una vez más?", "categoria": "pasado" },
  { "pregunta": "¿Qué error agradecés haber cometido?", "categoria": "pasado" },
  { "pregunta": "¿Qué recuerdo te formó sin que lo supieras?", "categoria": "pasado" },
  { "pregunta": "¿Qué parte de tu infancia te sigue acompañando?", "categoria": "pasado" },
  { "pregunta": "¿Qué persona del pasado entendés mejor hoy?", "categoria": "pasado" },
  { "pregunta": "¿Qué etapa cerraste recién con los años?", "categoria": "pasado" },
  { "pregunta": "¿Qué momento te gustaría revivir solo una vez más?", "categoria": "pasado" },
  { "pregunta": "¿Qué error agradecés haber cometido?", "categoria": "pasado" },
  { "pregunta": "¿Qué recuerdo te formó sin que lo supieras?", "categoria": "pasado" },
  { "pregunta": "¿Qué parte de tu infancia te sigue acompañando?", "categoria": "pasado" },
  { "pregunta": "¿Qué persona del pasado entendés mejor hoy?", "categoria": "pasado" },
  { "pregunta": "¿Qué etapa cerraste recién con los años?", "categoria": "pasado" },
  { "pregunta": "¿Qué verdad ocultás por comodidad?", "categoria": "picantes" },
  { "pregunta": "¿Qué parte tuya evitás mostrar?", "categoria": "picantes" },
  { "pregunta": "¿Qué excusa te repetís demasiado?", "categoria": "picantes" },
  { "pregunta": "¿Qué límite rompiste alguna vez?", "categoria": "picantes" },
  { "pregunta": "¿Qué deseo te cuesta admitir?", "categoria": "picantes" },
  { "pregunta": "¿Qué cosa ridícula te da felicidad?", "categoria": "divertidas" },
  { "pregunta": "¿Qué manía tuya es inexplicable?", "categoria": "divertidas" },
  { "pregunta": "¿Qué harías si nadie te juzgara por un día?", "categoria": "divertidas" },
  { "pregunta": "¿Qué talento inútil te salva del aburrimiento?", "categoria": "divertidas" },
  { "pregunta": "¿Qué costumbre rara tenés?", "categoria": "divertidas" },
  { "pregunta": "Decí una virtud de cada persona en la mesa.", "categoria": "retos" },
  { "pregunta": "Contá algo bueno que te haya pasado hoy.", "categoria": "retos" },
  { "pregunta": "Mandá un mensaje lindo a alguien.", "categoria": "retos" },
  { "pregunta": "Aplaudí a alguien por algo que hizo bien.", "categoria": "retos" },
  { "pregunta": "¿Qué te hace reír mucho?", "categoria": "niños" },
  { "pregunta": "¿Qué te gusta hacer cuando estás aburrido?", "categoria": "niños" },
  { "pregunta": "¿Qué te da miedo por la noche?", "categoria": "niños" },
  { "pregunta": "¿Qué cosa aprendiste jugando?", "categoria": "niños" },
  { "pregunta": "¿Qué parte de tu día disfrutás más sin darte cuenta?", "categoria": "conocernos" },
{ "pregunta": "¿Qué te calma casi de inmediato?", "categoria": "conocernos" },
{ "pregunta": "¿Qué costumbre tuya dice mucho de vos?", "categoria": "conocernos" },
{ "pregunta": "¿Qué te hace sentir en casa?", "categoria": "conocernos" },
{ "pregunta": "¿Qué cosa simple valorás mucho?", "categoria": "conocernos" },
{ "pregunta": "¿Qué parte de tu personalidad sale con muy poca gente?", "categoria": "conocernos" },

{ "pregunta": "¿Qué parte de tu vida sentís que todavía está en pausa?", "categoria": "profundas" },
{ "pregunta": "¿Qué miedo aprendiste a disimular bien?", "categoria": "profundas" },
{ "pregunta": "¿Qué verdad evitaste durante mucho tiempo?", "categoria": "profundas" },
{ "pregunta": "¿Qué te dolió más de lo que admitís?", "categoria": "profundas" },
{ "pregunta": "¿Qué conversación sabés que necesitás tener?", "categoria": "profundas" },
{ "pregunta": "¿Qué parte de vos necesitó más cuidado?", "categoria": "profundas" },

{ "pregunta": "¿Qué gesto te hace sentir realmente querido?", "categoria": "relaciones" },
{ "pregunta": "¿Qué vínculo te enseñó a decir que no?", "categoria": "relaciones" },
{ "pregunta": "¿Qué relación te cambió la forma de amar?", "categoria": "relaciones" },
{ "pregunta": "¿Qué aprendiste observando una pareja cercana?", "categoria": "relaciones" },
{ "pregunta": "¿Qué te cuesta pedir en una relación?", "categoria": "relaciones" },
{ "pregunta": "¿Qué persona te conoce mejor de lo que creés?", "categoria": "relaciones" },

{ "pregunta": "¿Qué error te enseñó más de lo que dolió?", "categoria": "crecimiento" },
{ "pregunta": "¿Qué hábito estás intentando cambiar ahora?", "categoria": "crecimiento" },
{ "pregunta": "¿Qué aprendizaje te llegó tarde, pero llegó?", "categoria": "crecimiento" },
{ "pregunta": "¿Qué parte de vos se volvió más fuerte?", "categoria": "crecimiento" },
{ "pregunta": "¿Qué límite aprendiste a poner?", "categoria": "crecimiento" },
{ "pregunta": "¿Qué versión tuya estás dejando atrás?", "categoria": "crecimiento" },

{ "pregunta": "¿Qué sueño postergás por miedo y no por falta de ganas?", "categoria": "sueños" },
{ "pregunta": "¿Qué te gustaría intentar aunque salga mal?", "categoria": "sueños" },
{ "pregunta": "¿Qué vida alternativa imaginás a veces?", "categoria": "sueños" },
{ "pregunta": "¿Qué proyecto sentís más propio?", "categoria": "sueños" },
{ "pregunta": "¿Qué te gustaría animarte a decir que sí?", "categoria": "sueños" },
{ "pregunta": "¿Qué sueño te emociona solo pensarlo?", "categoria": "sueños" },

{ "pregunta": "¿Qué momento te gustaría revivir solo una vez más?", "categoria": "pasado" },
{ "pregunta": "¿Qué error agradecés haber cometido?", "categoria": "pasado" },
{ "pregunta": "¿Qué recuerdo te formó sin que lo supieras?", "categoria": "pasado" },
{ "pregunta": "¿Qué parte de tu infancia te sigue acompañando?", "categoria": "pasado" },
{ "pregunta": "¿Qué persona del pasado entendés mejor hoy?", "categoria": "pasado" },
{ "pregunta": "¿Qué etapa cerraste recién con los años?", "categoria": "pasado" },

{ "pregunta": "¿Qué parte tuya defendés hoy sin culpa?", "categoria": "autoestima" },
{ "pregunta": "¿Qué logro tuyo no fue casualidad?", "categoria": "autoestima" },
{ "pregunta": "¿Qué cualidad tuya te sostiene en días difíciles?", "categoria": "autoestima" },
{ "pregunta": "¿Qué versión tuya te gusta más?", "categoria": "autoestima" },
{ "pregunta": "¿Qué cosa aprendiste a respetar de vos?", "categoria": "autoestima" },
{ "pregunta": "¿Qué fuerza descubriste en vos?", "categoria": "autoestima" },

{ "pregunta": "¿Qué verdad ocultás por comodidad?", "categoria": "picantes" },
{ "pregunta": "¿Qué parte tuya evitás mostrar?", "categoria": "picantes" },
{ "pregunta": "¿Qué excusa te repetís demasiado?", "categoria": "picantes" },
{ "pregunta": "¿Qué límite rompiste alguna vez?", "categoria": "picantes" },
{ "pregunta": "¿Qué deseo te cuesta admitir?", "categoria": "picantes" },

{ "pregunta": "¿Qué cosa ridícula te da felicidad?", "categoria": "divertidas" },
{ "pregunta": "¿Qué manía tuya es inexplicable?", "categoria": "divertidas" },
{ "pregunta": "¿Qué harías si nadie te juzgara por un día?", "categoria": "divertidas" },
{ "pregunta": "¿Qué talento inútil te salva del aburrimiento?", "categoria": "divertidas" },
{ "pregunta": "¿Qué costumbre rara tenés?", "categoria": "divertidas" },

{ "pregunta": "Decí una virtud de cada persona en la mesa.", "categoria": "retos" },
{ "pregunta": "Contá algo bueno que te haya pasado hoy.", "categoria": "retos" },
{ "pregunta": "Mandá un mensaje lindo a alguien.", "categoria": "retos" },
{ "pregunta": "Aplaudí a alguien por algo que hizo bien.", "categoria": "retos" },

{ "pregunta": "¿Qué te hace reír mucho?", "categoria": "niños" },
{ "pregunta": "¿Qué te gusta hacer cuando estás aburrido?", "categoria": "niños" },
{ "pregunta": "¿Qué te da miedo por la noche?", "categoria": "niños" },
{ "pregunta": "¿Qué cosa aprendiste jugando?", "categoria": "niños" }


]
